-- MySQL Script generated by MySQL Workbench
-- Fri Nov  8 09:50:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editora` (
  `ideditora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `localidade` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ideditora`),
  UNIQUE INDEX `ideditora_UNIQUE` (`ideditora` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `idlivro` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `disponivel` TINYINT NOT NULL,
  `idioma` VARCHAR(30) NOT NULL,
  `data_de_publicacao` VARCHAR(45) NOT NULL,
  `autor_idautor` INT NOT NULL,
  `editora_ideditora` INT NOT NULL,
  PRIMARY KEY (`idlivro`),
  INDEX `fk_livro_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  INDEX `fk_livro_editora1_idx` (`editora_ideditora` ASC) VISIBLE,
  CONSTRAINT `fk_livro_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `mydb`.`autor` (`idautor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`editora_ideditora`)
    REFERENCES `mydb`.`editora` (`ideditora`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `idemprestimo` INT NOT NULL AUTO_INCREMENT,
  `devolucao` DATE NOT NULL,
  `dia_do_emprestimo` TIMESTAMP NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  INDEX `fk_emprestimo_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_emprestimo_livro1_idx` (`livro_idlivro` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `avaliacao_funcionario` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `funcionario_idfuncionario` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `avaliacao` DECIMAL(3,2) NOT NULL,  -- Ex: avaliação de 0.00 a 5.00
  `data_avaliacao` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_funcionario_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  INDEX `fk_avaliacao_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_funcionario`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use mydb;
INSERT INTO `mydb`.`avaliacao_funcionario` 
(`funcionario_idfuncionario`, `cliente_idcliente`, `avaliacao`) 
VALUES 
(1, 2, 4.50),
(1, 3, 3.80),
(1, 4, 4.10),
(2, 1, 5.00),
(2, 3, 4.00),
(2, 5, 4.60),
(3, 2, 3.90),
(3, 4, 4.30),
(4, 1, 5.00),
(4, 5, 4.20);

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("123.456.789-00", "(62) 98419-0231", "Julia", 20080601);

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("987.654.321-01", "(11) 98765-4321", "Felipe", 20080602);

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("456.789.123-02", "(21) 99876-5432", "Atamara", "20080603");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("321.654.987-03", "(31) 98765-6543", "Ana Silva", "20080604");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("789.123.456-04", "(41) 99876-7654", "Pedro Santos", "20080605");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("234.567.890-059", "(51) 98765-8765", "Maria Oliveira", "20080606");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("890.123.456-06", "(61) 99876-9876", "João Souza", "20080607");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("567.890.123-07", "(71) 98765-0987", "Carla Martins", "20080608");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("345.678.901-08", "(81) 99876-12341", "Lucas Pereira", "20080609");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("901.234.567-09", "(91) 98765-2345", "Fernanda Costa", "20080610");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("678.901.234-10", "(12) 99876-34561", "Rafael Ferreira", "20080611");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("432.109.876-11", "(22) 98765-4567", "Juliana Almeida", "20080612");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("210.987.654-12", "(32) 99876-5678", "Marcos Rodrigues", "20080613");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("876.543.210-13", "(42) 98765-6789", "Camila Cardoso", "20080614");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("543.210.987-14", "(52) 99876-7890", "Bruno Gonçalves", "20080615");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("765.432.109-15", "(62) 98765-8901", "Mariana Ramos", "20080616");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("987.654.321-160", "(72) 99876-9012", "André Lima", "20080617");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("234.567.890-17", "(82) 98765-0123", "Laura Carvalho", "20080618");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("890.123.456-18", "(92) 99876-1234", "Tiago Gomes", "20080619");

INSERT INTO cliente (cpf, telefone, nome, data_de_nascimento) 
VALUES ("345.678.901-19", "(13) 98765-2345", "Renata Barbosa", "20080620");




INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Bruno Santos", "123.456.789-01", 1412, "20000620","(13) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Clara Oliveira", "123.456.789-02", 1412, "20010620","(23) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Daniel Costa", "123.456.789-03", 1412, "20020620","(33) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Elisa Pereira", "123.456.789-04", 1412, "20030620","(43) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Felipe Rodrigues", "123.456.789-05", 1412, "20040620","(53) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Gabriela Almeida", "123.456.789-06", 1412, "20050620","(63) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Henrique Lima", "123.456.789-07", 1412, "20060620","(73) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Isabela Cardoso", "123.456.789-08", 1412, "20070620","(83) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("João Carvalho", "123.456.789-09", 1412, "20080620","(93) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Laura Sousa", "123.456.789-10", 1412, "20090620","(103) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Mateus Fernandes", "123.456.789-11", 1412, "20100620","(113) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Natália Gomes", "123.456.789-12", 1412, "20110620","(123) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Otávio Miranda", "123.456.789-13", 1412, "20120620","(133) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Paula Barbosa", "123.456.789-14", 1412, "20130620","(143) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Rafael Martins", "123.456.789-15", 1412, "20140620","(153) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Sofia Ribeiro", "123.456.789-16", 1412, "20150620","(163) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Thiago Gonçalvess", "123.456.789-17", 1412, "20160620","(173) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Valentina Santos", "123.456.789-18", 1412, "20170620","(183) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("William Oliveira", "123.456.789-19", 1412, "20180620","(193) 88765-2345");

INSERT INTO funcionario (nome, cpf, salario, data_de_nascimento,telefone) 
VALUES ("Yasmin Ribeiro", "123.456.789-20", 1412, "20190620","(203) 88765-2345");




INSERT INTO editora (nome,localidade) 
VALUES ("Editora Sentimentos", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Misteriosos Editores", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Love Stories Publishing", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Storia Antica", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Future Fiction", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Al-Mutanabbi Publishing", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Philosophische Verlag", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Manga Publishing Co ", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Libros para el Alma", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Enchanted Tales", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Noir Editore", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Imperial Romance Press", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Editora Reflexão", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Spannende Geschichten", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Épica Edições", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Spannende Edições", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Épica Edições R.", "Russia");

INSERT INTO editora (nome,localidade) 
VALUES ("Noir Edições", "Brazil");

INSERT INTO editora (nome,localidade) 
VALUES ("Noir Edições Ca.", "Canadá");

INSERT INTO editora (nome,localidade) 
VALUES ("Noir Edições Cr.", "Catar");




INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Gabriel García Márquez", "Colombiano","20000102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Haruki Murakami", "Japonês","20010102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Jane Austen", "Britânica","20020102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Franz Kafka", "Checo","20030102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("J.K. Rowling", "Britânica","20040102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Leo Tolstoy", "Russo","20050102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Paulo Coelho", "Brasileiro","20060102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Ernest Hemi","fdgvsdfs","20060102");


INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Chimamanda Ngozi Adichie", "Nigeriana","20080102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES("Isabel Allende", "Chilena","20090102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Yukio Mishima", "Japonês","20100102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Albert Camus", "Francês","20110102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Toni Morrison", "Americana","20120102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Milan Kundera", "Checo","20130102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Mario Vargas Llosa", "Peruano","20140102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Elena Ferrante", "Italiana","20150102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Virginia Woolf", "Britânica","20160102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Salman Rushdie", "Britânico","20170102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Orhan Pamuk", "Turco","20180102");

INSERT INTO autor (nome,nacionalidade,data_de_nascimento) 
VALUES ("Murilo Rubião", "Brasileiro","20190102");




INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Realismo Mágico"," Cem Anos de Solidão",1,"Italiano",20010922,1,2);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Norwegian Wood", "Ficção Contemporânea",1,"Inglês",20020922,17,20);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Orgulho e Preconceito", "Romance Clássico",1,"Português",20030922,15,17);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("A Metamorfose", "Ficção Absurda",1,"Inglês",20040922,12,4);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Harry Potter e a Pedra Filosofal", "Fantasia",1,"Italiano",20050922,10,15);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Guerra e Paz", "Romance Histórico",1,"Português",20060922,8,8);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("O Alquimista", "Ficção Espiritual",1,"Inglês",20070922,4,19);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("O Velho e o Mar", "Novela",1,"Português",20080922,5,16);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Americanah", "Ficção Contemporânea",1,"Turco",20090922,11,7);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("A Casa dos Espíritos", "Realismo Fantástico",1,"Português",20100922,14,18);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("O Maravilhoso País de Oz", "Literatura Infantil",1,"Inglês",20110922,1,2);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("O Estrangeiro", "Ficção Existencialista",1,"Inglês",20120922,18,20);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Amada", "Romance Afro-Americano",1,"Turco",20130922,9,1);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("A Insustentável Leveza do Ser", "Romance Filosófico",1,"Inglês",20140922,6,18);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("A Invenção de Morel", "Ficção Científica",1,"Italiano",20150922,9,2);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("Mrs. Dalloway", "Romance Afro-Americano",1,"Italiano",20160922,2,9);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("logo mal", "Realismo Fantástico",1,"Inglês",20170922,2,2);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("os tres porquinhos", "Sátira Fantástica",1,"Italiano",20170922,2,2);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("logo bom", "Romance Afro-Americano",1,"Português",20170922,2,2);

INSERT INTO livro (genero,titulo,disponivel,idioma,data_de_publicacao,autor_idautor,editora_ideditora) 
VALUES ("os dois porquinhos", "Sátira Fantástica",1,"Italiano",20170922,2,2);




INSERT INTO `mydb`.`emprestimo` (`devolucao`, `dia_do_emprestimo`, `funcionario_idfuncionario`, `cliente_idcliente`, `livro_idlivro`)
VALUES 
('2024-12-01', CURRENT_TIMESTAMP, 4, 22, 8),
('2024-12-05', CURRENT_TIMESTAMP, 3, 22, 9),
('2024-12-10', CURRENT_TIMESTAMP, 2, 22, 10),
('2024-12-15', CURRENT_TIMESTAMP, 1, 22, 11),
('2024-12-20', CURRENT_TIMESTAMP, 4, 22, 12),
('2024-12-22', CURRENT_TIMESTAMP, 2, 22, 13),
('2024-12-25', CURRENT_TIMESTAMP, 3, 22, 14),
('2024-12-30', CURRENT_TIMESTAMP, 1, 22, 15),
('2025-01-02', CURRENT_TIMESTAMP, 4, 22, 16),
('2025-01-05', CURRENT_TIMESTAMP, 2, 22, 17);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001201,CURRENT_TIMESTAMP,4,1,8);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001202,CURRENT_TIMESTAMP,1,4,7);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001203,CURRENT_TIMESTAMP,2,16,2);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001204,CURRENT_TIMESTAMP,5,1,7);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001205,CURRENT_TIMESTAMP,4,8,2);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001206,CURRENT_TIMESTAMP,3,4,5);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001207,CURRENT_TIMESTAMP,9,13,20);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001208,CURRENT_TIMESTAMP,8,12,16);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001209,CURRENT_TIMESTAMP,10,18,11);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001210,CURRENT_TIMESTAMP,11,6,10);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001211,CURRENT_TIMESTAMP,7,8,9);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001212,CURRENT_TIMESTAMP,6,10,11);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001213,CURRENT_TIMESTAMP,17,13,5);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001214,CURRENT_TIMESTAMP,14,2,13);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001215,CURRENT_TIMESTAMP,15,12,13);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001216,CURRENT_TIMESTAMP,9,12,13);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001217,CURRENT_TIMESTAMP,6,11,17);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001218,CURRENT_TIMESTAMP,18,5,2);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001219,CURRENT_TIMESTAMP,16,2,8);

INSERT INTO emprestimo(devolucao,dia_do_emprestimo,funcionario_idfuncionario,cliente_idcliente,livro_idlivro)
VALUES (20001220,CURRENT_TIMESTAMP,5,1,10);
